# Generated by Django 4.2.2 on 2023-06-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_h', models.BinaryField()),
                ('add_l', models.BinaryField()),
                ('chan', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=32)),
                ('schede', models.ManyToManyField(blank=True, related_name='topics', to='mqtt_lora.scheda')),
            ],
        ),
    ]
