# Generated by Django 4.2.2 on 2023-06-16 14:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_lora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='nome',
            field=models.TextField(max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retain', models.BooleanField()),
                ('date_time', models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 16, 14, 24, 56, 885377))),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='mqtt_lora.topic')),
            ],
        ),
    ]
