# Generated by Django 4.2.2 on 2023-06-16 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_lora', '0003_alter_message_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 16, 15, 25, 3, 948409)),
        ),
    ]
