# Generated by Django 4.2.2 on 2023-06-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_lora', '0006_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(default='empty', max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='retain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mqtt_lora.topic'),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='add_h',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='add_l',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scheda',
            name='chan',
            field=models.IntegerField(),
        ),
    ]
