# Generated by Django 4.2.2 on 2023-06-17 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_lora', '0007_alter_message_message_alter_message_retain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mqtt_lora.topic'),
        ),
    ]
