# Generated by Django 4.2.2 on 2023-06-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_lora', '0008_alter_message_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
