# Generated by Django 4.2.2 on 2023-06-17 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_lora', '0009_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField(max_length=100)),
                ('retain', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt_lora.topic')),
            ],
        ),
    ]
